### ISSUE TITLE
It seem that the p2 repository for obeo is no longer working

### ISSUE THREAD

**Issue by mefju7** [mbarbero/fr.obeo.releng.targetplatform#69]
The last 2 weeks i get an error when trying to access the p2. repository.

**Comment by mbarbero** [comment]
Both http://mbarbero.github.io/fr.obeo.releng.targetplatform/p2/ and http://mbarbero.github.io/fr.obeo.releng.targetplatform/p2/latest/ works for me. 

Can you elaborate about the specific error you get?

**Comment by mefju7** [comment]
When trying to use the install from Eclipse/neon, the first one gives an org.eclipse.equinox.p2.core.ProvisionException with 
```
Unable to read repository at http://mbarbero.github.io/fr.obeo.releng.targetplatform/p2/.
Unable to read repository at http://mbarbero.github.io/fr.obeo.releng.targetplatform/p2/.
Unable to read repository at http://mbarbero.github.io/fr.obeo.releng.targetplatform/p2/2.0.
No repository found at http://mbarbero.github.io/fr.obeo.releng.targetplatform/p2/2.0/2.0.0.201403031738.
```
I am not able to download a content.xml/jar from the location, which seems to be the error.

The latter gives me http 404  page not found error in the web browser.

**Comment by mbarbero** [comment]
What kind of error?

**Comment by mbarbero** [comment]
I see no solution other than asking your company whether they block github.com. Thanks for reporting the issue anyway.

**Comment by mefju7** [comment]
Yes, it was blocked. I traced the p2 content until http://mbarbero.github.io/fr.obeo.releng.targetplatform/p2/2.1/2.1.1.201410251450/content.jar and that one was blocked. 
Thanks for the fast reponse.
