### ISSUE TITLE
When to generate the tpd file during a Tycho build

### ISSUE THREAD

**Issue by JonasHelming** [mbarbero/fr.obeo.releng.targetplatform#73]
Hi, 

first thank you for this great tool.
We would like to use tpd files exclusively for setting the target platform.

We tried to generate the target file using the tycho-eclipserun-plugin as described in the example. The problem is that the target file is generated to late, even if we use the validation phase for the generation and thus the build fails as it cannot find the target file. Tychos seems to resolve the target already in this phase.

Do you have a solution for this problem?

**Comment by mbarbero** [comment]
Hi Jonas.

I'm glad you find it helpful. AFAICT, Tycho uses maven extension mechanism
to hook up very early in the maven dependencies resolution mechanism, so
there are little chances you can use a generated .target from the same
maven run. My best advice would be to extract the .target generation in a
separate pom and run two mvn calls in a row:

$ mvn clean <phase_you_bound_the_eclipserun_to> -f
releng/targetplatform/pom.xml
$ mvn clean verify

Cheers,

**Comment by JonasHelming** [comment]
OK, thanks for the information!
