### ISSUE TITLE
How to reference a specific version?

### ISSUE THREAD

**Issue by maffeis** [mbarbero/fr.obeo.releng.targetplatform#82]
Looking at your example:

location "http://download.eclipse.org/releases/juno/" {
    // select the most recent version of EMF after 2.7.0
    org.eclipse.emf.sdk.feature.group 2.7.0
    // select the most recent eclipse.rcp feature within the given range 
    org.eclipse.rcp.feature.group [4.0.0,4.3.0)
}

What if I would like to embed the specific version 2.7.0 of EMF in the target, even if there is a newer version available? I tried constructs such as [2.7.0] but I'm always getting a validation error.

**Comment by pcdavid** [comment]
You can use `[2.7.0,2.7.0]` to force a specific version.

Completion (_Ctrl-Space_) will propose among the candidates a pre-configured range which matches exactly each of the versions available, up to the qualifier (for example `org.junit [4.12.0.v201504281640,4.12.0.v201504281640]`).

**Comment by maffeis** [comment]
That works like a charm, thanks!
