### ISSUE TITLE
Change Request : Add optional id in the TPD language

### ISSUE THREAD

**Issue by microwan** [mbarbero/fr.obeo.releng.targetplatform#83]
Hello ,

### **in the target file :**
id attribute is necessary to use repository with credentials (for protected update with credentials)
`<repository id="idname" location="http://idname.test.com/"/>`
for pom/maven generation purpose

the enhancement is to add optional id in the TPD Language

### **in the tpd file :**
`location "http://idname.test.com/" id "idname"
{
   org.eclipse.myfeature.group
}`

it will permit to generate the target file with id attribute

          Best regards

                                Erwan

**Comment by mbarbero** [comment]
You can already ;) See the README:

> A location may have an ID that can be written before or after the URI. This is useful if you want to apply some maven stuff (providing a password, a mirror…) for this repository (see #17 for examples).
> 
>` location kepler "http://download.eclipse.org/releases/kepler/" `

**Comment by microwan** [comment]
It works perfectly ;-)
TPD editor is so powerful.

**Comment by mbarbero** [comment]
Thanks for the feedbacks. Glad it helps!
